### ISSUE TITLE
Week 5 exercise 2

### ISSUE THREAD

**Issue by neodyymi** [jttoivon/x#10]
Not sure what happened here, but suddenly had no tests to pass:
![image](https://user-images.githubusercontent.com/9444224/52595266-2687a600-2e56-11e9-8f83-712c4c4e04f1.png)

**Comment by neodyymi** [comment]
Also now that I looked deeper. TMC says the submission is OK, but it's not granting points.

**Comment by jttoivon** [comment]
This happens usually when your program crashes. You should first run your program, for example by:
python3 src/cycling_weather.py
The error message it gives is quite clear.

The workflow is:
- First run your program: python3 src/cycling_weather.py
- If it works as you expect,  then tmc test
- If it passes the tests, then tmc submit
