### ISSUE TITLE
Week 4 exercise 2 (power of series)

### ISSUE THREAD

**Issue by neodyymi** [jttoivon/x#8]
Exercise template is broken:
```
#!/usr/bin/env python3

    return None
    
def main():
    return
    
if __name__ == "__main__":
    main()
```

It's missing `def powers_of_series(s, k):` in the least.

**Comment by jttoivon** [comment]
Thanks for the report!

The template is fixed now but is you say 'tmc update' it might not overwrite the old version if you have modified it.

The correct template is:
#!/usr/bin/env python3


def powers_of_series(s, k):
    return None
    
def main():
    return
    
if __name__ == "__main__":
    main()
